package it.polimi.ingsw.controller.actions;

public enum Actions {
    MARKETPURCHASE,
    DEVCARDPURCHASE,
    ACTIVATELEADER,
    ACTIVATEPRODUCTION,
    ACTIVATEBASIC,
    ACTIVATELEADERPRODUCTION,
    DISCARDRESOURCE,
    DISCARDLEADER,
    UPDATEWAREHOUSE,
    DEPOSIT,
    DEVCARDWITHDRAW,
    LORENZO
}
